# Auftrag 1 - Bug 2 (behoben): Action-Name korrigiert.

name: A2 Python-Version

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Version ausgeben
        run: python --version
